language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
    - "pip install -r requirements.txt"
    - "pip install coverage"
    - "pip install coveralls"
    - "pip install codecov"

script: 
    - "python tests.py"
    - "pytest"

notifications:
  slack:
    #  rooms:
    #    - ':<token>#steniq'
    on_success: always
    on_failure: always
